name: Tripper CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [19.6.0]

        steps:
            - name: Checkout Source Code.
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Check NPM Version
              run: npm -v

            - run: npm ci

            - name: Create ENV File
              working-directory: src/config/envs
              run: |
                  pwd
                  echo pwd
                  touch .env.development
                  echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env.development
                  echo PORT=${{ secrets.PORT }} >> .env.development
                  echo RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }} >> .env.development
                  echo RDS_PORT=${{ secrets.RDS_PORT }} >> .env.development
                  echo RDS_ID=${{ secrets.RDS_ID }} >> .env.development
                  echo RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} >> .env.development
                  echo RDS_DATABASE=${{ secrets.RDS_DATABASE }} >> .env.development
                  echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env.development
                  echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env.development
                  echo REDIS_USERNAME=${{ secrets.REDIS_USERNAME }} >> .env.development
                  echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env.development
                  echo SWAGGER_ID=${{ secrets.SWAGGER_ID }} >> .env.development
                  echo SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }} >> .env.development
                  echo KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }} >> .env.development
                  echo KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }} >> .env.development
                  echo NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} >> .env.development
                  echo NAVER_CLIENT_SECRET_KEY=${{ secrets.NAVER_CLIENT_SECRET_KEY }} >> .env.development
                  echo NAVER_CALLBACK_URL=${{ secrets.NAVER_CALLBACK_URL }} >> .env.development
                  echo JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }} >> .env.development
                  echo JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }} >> .env.development
                  echo S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }} >> .env.development
                  echo S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }} >> .env.development
                  echo S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} >> .env.development
                  echo S3_REGION=${{ secrets.S3_REGION }} >> .env.development

            - name: Build Server Files
              working-directory: ./
              run: npm run build --if-present

            - name: Check eslint
              run: npm run lint
