name: Tripper CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [19.6.0]

        steps:
            - name: Checkout Source Code.
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: npm install
              run: npm install

            - name: npm ci
              run: npm ci

            - name: Build Server Files
              run: npm run build --if-present
