name: Tripper CI

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                node-version: [19.6.0]

        steps:
            - name: Checkout Source Code.
              uses: action/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Check NPM Version
              uses: npm -v

            - run: npm ci

            - run: npm run build --if-present
